name: deploy-container

on:
  push:
    branches:
      - master #branch in which an event runs and triggers ci cd
    paths:
      - 'packages/container/**' #path where the changes are going to occur

defaults:
  run:
    working-directory: packages/container #container folder where we want to run our commands like npm install

jobs:
  build:
    runs-on: ubuntu-latest #virtual machine we need

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: chrislennon/action-aws-cli@v1.1
      - run: aws s3 sync dist s3://${{secrets.AWS_S3_BUCKET_NAME}}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}