name: deploy-marketing

on:
  push:
    branches:
      - master #branch in which an event runs and triggers ci cd
    paths:
      - 'packages/marketing/**' #path where the changes are going to occur

defaults:
  run:
    working-directory: packages/marketing #marketing folder where we want to run our commands like npm install

jobs:
  build:
    runs-on: ubuntu-latest #virtual machine we need

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync dist s3://${{secrets.AWS_S3_BUCKET_NAME}}/marketing/latest #this is to automatically update the files in s3
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: "us-east-2"

      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/marketing/latest/remoteEntry.js" #this is to automatically serve the cloudfront with the latest remoteEntry.js file after js files changes
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: "us-east-2"